# Generated by Django 5.2.4 on 2025-07-21 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_router', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygon',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
